Repository redhat-developer/rhdh-operator, pull requests merged in 2025-09, with the labels that each got.

#1571 [release-1.7] doc: add backend_secret config to orchestrator (#1567)
  docs/orchestrator.md
  examples/orchestrator.yaml
Labels: approved, lgtm

#1591 Update checkout action to use SHA instead of ref
  .github/workflows/pr-bundle-diff-checks.yaml
Labels: Review effort 1/5

#1599 fix(ci): Make sure to checkout the PR branch before pushing the bundle diff generated
  .github/workflows/pr-bundle-diff-checks.yaml
Labels: Review effort 2/5

#1652 ci(nightly): Always display Operator logs at the end of the E2E tests
  tests/e2e/e2e_suite_test.go
Labels: Review effort 2/5, Tests
