Repository redhat-developer/rhdh-operator, pull requests merged in 2025-01, with the labels that each got.

#608 chore: support easily testing from stage...
  .rhdh/scripts/install-rhdh-catalog-source.sh
Labels: approved, lgtm

#621 ci: Fix the E2E nightly upgrade tests
  tests/e2e/testdata/rhdh-operator-1.3.yaml
  tests/e2e/testdata/rhdh-operator-1.4.yaml
Labels: approved, lgtm

#582 Configure other than Backstage container to mount PVC volume to
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha2/zz_generated.deepcopy.go
  api/v1alpha3/zz_generated.deepcopy.go
  bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml
  bundle/rhdh/manifests/rhdh-default-config_v1_configmap.yaml
  config/profile/rhdh/default-config/deployment.yaml
  docs/configuration.md
  pkg/model/deployment.go
  pkg/model/pvcs.go
  pkg/model/pvcs_test.go
  pkg/model/runtime.go
  pkg/model/testdata/multi-pvc-containers.yaml
  pkg/model/testdata/multicontainer-deployment.yaml
  pkg/utils/pod-mutator.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved

#625 ci: Fix issue preventing the bundle diff checker job from committing changes detected
  .github/workflows/pr-bundle-diff-checks.yaml
Labels: approved, lgtm

#631 Fix replicas in example
  examples/rhdh-cr-with-app-configs.yaml
Labels: approved

#601 chore(renovate): Remove EOL 1.2.x from the Renovate config
  .github/renovate.json
Labels: approved

#638 chore: migrate from janus showcase to gh/rhd/rhdh and quay.io/rhdh-community/rhdh (RHIDP-1022)
  README.md
  docs/configuration.md
  examples/showcase-config.yaml
Labels: approved, lgtm

#648 ci: Fix the changed files detection when running some of the Workflows
  .github/workflows/next-container-build.yaml
  .github/workflows/pr-container-build.yaml
  .github/workflows/pr.yaml
Labels: approved, lgtm

#649 ci: Fix container image build workflows running from forks
  .github/workflows/next-container-build.yaml
  .github/workflows/pr-container-build.yaml
Labels: approved, lgtm

#609 Default secrets
  docs/configuration.md
  pkg/model/appconfig.go
  pkg/model/appconfig_test.go
  pkg/model/configmapenvs.go
  pkg/model/configmapfiles.go
  pkg/model/db-statefulset.go
  pkg/model/deployment.go
  pkg/model/dynamic-plugins.go
  pkg/model/pvcs.go
  pkg/model/secretenvs.go
  pkg/model/secretenvs_test.go
  pkg/model/secretfiles.go
  pkg/model/secretfiles_test.go
  pkg/model/testdata/raw-multi-secret.yaml
  pkg/utils/pod-mutator.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved

#664 Patch Operator default configuration with Platform specifics
  .rhdh/scripts/install-rhdh-catalog-source.sh
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha2/zz_generated.deepcopy.go
  api/v1alpha3/zz_generated.deepcopy.go
  bundle/backstage.io/manifests/backstage-operator.clusterserviceversion.yaml
  bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml
  bundle/rhdh/manifests/rhdh-default-config_v1_configmap.yaml
  cmd/main.go
  config/profile/rhdh/default-config/db-statefulset.yaml.k8s
  config/profile/rhdh/default-config/deployment.yaml.k8s
  config/profile/rhdh/default-config/service.yaml.k8s
  config/profile/rhdh/kustomization.yaml
  docs/profiles.md
  integration_tests/rhdh-config_test.go
  pkg/model/runtime.go
  pkg/utils/testdata/deployment.yaml
  pkg/utils/testdata/deployment.yaml.k8s
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved

#672 chore(E2E): Make sure the E2E tests can fully test that the application is reachable on K8s (using an Ingress on GH)
  .github/workflows/nightly.yaml
  Makefile
  tests/e2e/README.md
  tests/e2e/e2e_test.go
  tests/helper/helper_backstage.go
Labels: approved, lgtm, devtools-week

#723 add Update-Strategy for the Subscription
  .rhdh/scripts/install-rhdh-catalog-source.sh
Labels: approved, lgtm

#706 Deployed status as available deployment
  docs/design.md
  integration_tests/default-config_test.go
  internal/controller/backstage_controller.go
  internal/controller/watchers.go
  pkg/model/db-service.go
  pkg/model/db-statefulset.go
  pkg/utils/utils.go
Labels: approved
