Repository redhat-developer/rhdh-operator, pull requests merged in 2025-08, with the labels that each got.

#1480 chore: change behavior of filtered versions for restricted env.
  .rhdh/scripts/prepare-restricted-environment.sh
Labels: approved, lgtm

#1482 Add Network Policy for Orchestrator (#1481)
  bundle/rhdh/manifests/rhdh-plugin-deps_v1_configmap.yaml
  config/profile/rhdh/plugin-deps/sonataflow.yaml
  dist/rhdh/install.yaml
  docs/orchestrator.md
Labels: ok-to-test

#1522 chore: Update from ubi9/go-toolset:9.6-1754467841 to ubi9/go-toolset:9.6-1755529097
  .rhdh/docker/Dockerfile
  Dockerfile
Labels: approved, lgtm

#1536 chore: Remove EOL 1.5 from the nightly tests and disable it in the Renovate config
  .github/renovate.json
  .github/workflows/nightly-upgrade-test.yaml
  .github/workflows/nightly.yaml
  tests/e2e/e2e_upgrade_test.go
  tests/e2e/testdata/rhdh-operator-1.5.yaml
Labels: lgtm

#1486 Merge dynamic-plugins config
  bundle/backstage.io/manifests/backstage-operator.clusterserviceversion.yaml
  bundle/rhdh/manifests/backstage-operator.clusterserviceversion.yaml
  docs/configuration.md
  examples/orchestrator.yaml
  integration_tests/cr-compatibility_test.go
  internal/controller/plugin-deps.go
  pkg/model/appconfig.go
  pkg/model/configmapenvs.go
  pkg/model/configmapenvs_test.go
  pkg/model/configmapfiles.go
  pkg/model/db-secret.go
  pkg/model/db-service.go
  pkg/model/db-statefulset.go
  pkg/model/deployment.go
  pkg/model/dynamic-plugins.go
  pkg/model/dynamic-plugins_test.go
  pkg/model/interfaces.go
  pkg/model/model_tests.go
  pkg/model/pvcs.go
  pkg/model/route.go
  pkg/model/runtime.go
  pkg/model/secretenvs.go
  pkg/model/secretfiles.go
  pkg/model/secretfiles_test.go
  pkg/model/service.go
Labels: approved, lgtm

#1541 chore(deps): update ubi9-minimal runtime image to 9.6 and update go-toolset
  .rhdh/docker/Dockerfile
  Dockerfile
Labels: approved, lgtm

#1557 chore: Bump the Go version to 1.24 [RHIDP-8052]
  .github/renovate.json
  .github/workflows/nightly.yaml
  .github/workflows/pr.yaml
  .rhdh/docker/Dockerfile
  Dockerfile
  Makefile
  README.md
  go.mod
Labels: approved, lgtm
